[package]
name        = "mSkipList_mcpp"
version     = "0.1.0"
license     = "MIT"
authors     = ["Ximiaw"]
repo        = "https://github.com/Ximiaw/mSkipList_mcpp"

[targets.mSkipList_mcpp]
kind = "lib"

[build]
cxxflags     = ["-O3"]