[package]
name        = "mSkipList"
version     = "0.1.0"
description = "A generic Skip List data structure implemented in C++23, supporting multi-field data storage, arbitrary field as primary key, and custom memory allocation strategies."
license     = "MIT"
authors     = ["Ximiaw"]

[targets.mSkipList]
kind = "lib"